[theme]
primaryColor="#AAAAAA"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#A3998E"
textColor="#001A23"
font="sans serif"

[client]
showSidebarNavigation = false

[global]
developmentMode = false

[server]
headless = true
enableXsrfProtection = false
enableCORS = false